In [1]:
import numpy as np
print(np.__version__)
print(dir(np))

2.5.3
['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_

#### 1. 1차원 array 정의 및 사용하기

In [2]:
# 1. np.array(data) : 매개값으로 전달된  data를 numpy배열로 리턴
# np.array?

data = [1,2,3,4]
print(data, type(data))

# np.array : data를 ndarray로 변환해주는 함수
arr=np.array(data)
print(arr, type(arr))

# np.array는 요소의 데이터형이 다를 경우 : upcasting됨
arr = np.array([1,2,3,4.0])
print(arr, type(arr))

[1, 2, 3, 4] <class 'list'>
[1 2 3 4] <class 'numpy.ndarray'>
[1. 2. 3. 4.] <class 'numpy.ndarray'>


In [3]:
# 2. np.shape() : numpy배열의 크기를 리턴
a = 4
b = 4
c = 4
print(type(a), type(b), type(c))

# np.shape : array크기 확인
print(np.shape(arr))
print(arr.shape)

# np.shape?

<class 'int'> <class 'int'> <class 'int'>
(4,)
(4,)


#### 2. 2차원array(Matrix)

In [4]:
data = [[1,2,3],[4,5,6.0]]
arr = np.array(data)

print(arr, type(arr), arr.dtype, arr.shape)

[[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.ndarray'> float64 (2, 3)


In [5]:
# 3X3

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr, type(arr), arr.dtype, arr.shape)

# 주의할 점 : 요소의 갯수가 다를 경우 => 1차원 array로 생성
arr = np.array([[1,2,3],[4,5,6],[7,8]])
print(arr, type(arr), arr.dtype, arr.shape)

# 가능
arr = np.array([(1,2,3),[4,5,6],[7,8,9]])
print(arr, type(arr), arr.dtype, arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [6]:
arr = np.eye(5)
print(arr, arr.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] (5, 5)


In [7]:
arr = np.zeros(5)
print(arr, arr.shape)
print()

arr = np.zeros((3,3))
print(arr, arr.shape)

[0. 0. 0. 0. 0.] (5,)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)


In [8]:
arr = np.ones(5)
print(arr, arr.shape)

arr = np.ones((5,5))
print(arr, arr.shape)

[1. 1. 1. 1. 1.] (5,)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (5, 5)


#### 3. numpy 연산

>* numpy의 배열은 list와 비슷하지만 다음과 같은 점에서 다르다.
>    - 모든 원소가 `동일 자료형`이어야 한다.
>    - `원소의 갯수를 변경할 수 없다.`


##### 1) numpy.shape

* numpy에서 해당 `array의 형태(크기)`를 확인할 수 있는 함수이다. 이 함수는 정수를 리턴한다.
* shape(크기)를 확인함으로써 numpy배열에 몇개의 데이터가 있는지, 몇차원의 데이터인지를 확인
* 1차원 배열일 경우 (5,), 2차원 배열일 경우 (3, 4)의 형태로 린턴된다.

##### 2) numpy data type(dtype)

* int(8, 16,32, 64) : 부호가 있는 정수
* uint(8, 16, 32, 64) : 부호가 없는 정수
* float(16, 32, 64, 128) : 실수
* complex(64, 128, 256) : 복소수
* bool : boolean
* object : 파이썬의 object(객체)
* unicode : 유니코드

In [ ]:
# numpy 배열의 연산

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

# 사칙연산
print('numpy 배열 더하기 = \n', arr1 + arr2)
print('numpy 배열 빼기 = \n', arr2 - arr1)
print('numpy 배열 곱하기 = \n', arr1 * arr2)
print('numpy 배열 나누기 = \n', arr2 / arr1)

In [ ]:
# numpy함수 이용해 사칙연산
# print(dir(np))
print('numpy 배열 더하기 = \n', np.add(arr1, arr2))
print('numpy 배열 빼기 = \n', np.subtract(arr2, arr1))
print('numpy 배열 곱하기 = \n', np.multiply(arr1, arr2))
print('numpy 배열 나누기 = \n', np.divide(arr2, arr1))

##### 3) numpy array broadcasting

* numpy배열의 연산은 기본적으로 동일크기를 가져야 연산이 가능하지만, 배열이 크기가 다를 경우에 연산을 할 수 있도록 하기 위해서 numpy에서는 `broadcasting`라는 기능을 제공해 준다
* 즉, `broadcastig은 서로 크기가 다른 numpy배열의 연산이 가능`하도록 해주는 기능이다.

<img src = './images/22.데이터분석_numpy_01_broadcasting.png'>
<img src = './images/22.데이터분석_numpy_02_broadcasting.png'>

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,11,12])

print('numpy 배열 더하기 = \n', arr1 + arr2)
print('numpy 배열 빼기 = \n', arr1 - arr2)
print('numpy 배열 곱하기 = \n', arr1 * arr2)
print('numpy 배열 나누기 = \n', arr1 / arr2)
print('numpy 배열 2배 = \n', arr1*2)
print('numpy 배열 2제곱 = \n', arr1 **2)

In [ ]:
# 문1. 0부터 99까지의 정수가 저장된 ndarray객체를 만드시오.(arange()함수)

arr = np.arange(100)
print(arr, type(arr))

In [ ]:
# 문2. 구구단 3단의 결과가 저장된 ndarray 객체를 만드시오

arr = np.arange(1,10)*3
print(arr, type(arr))


In [ ]:
# 문3. 리스트에는 6개의 데이터가 저장되어 있습니다.
# 2행 3열의 ndarray로 변환하세요
data = [0,1,2,3,4,5]

arr = np.array(data)
arr.reshape(2,3)

In [ ]:
# 문4. 2차원 ndarray를 1차원 ndarray로 변환하세요
arr = np.array([[0,1,2],[3,4,5]])

arr = arr.flatten()  # flatten : 단조롭게 하다
print(arr)

In [ ]:
arr = np.array([[0,1,2],[3,4,5]])

arr = arr.reshape(6)
print(arr)

In [ ]:
# 문5. 4X5에 1이 저장된 ndarray객체를 만드시오.

arr = np.ones(20, dtype = int).reshape(4, 5)
print(arr)


In [ ]:
# 문6. 255로 채워진 10X10  크기의 ndarray 객체를 생성하세요.

arr = np.ones(100, dtype=int).reshape(10,10)
print(arr*255)


In [ ]:
# 문7. arr배열은 fload64타입입니다. 이를 np.int32타입으로 변경하세요.
arr = np.array([1.1, 2.1, 3.1])

int_arr = arr.astype(np.int32)
print(int_arr)

In [ ]:
# 참고. linspace(star, stop, num)
np.linspace(0, 10, 20)  # 0에서 10 사이는 20개의 포인트로 분할

##### 4) numpy array의 slicing과 indexing

* numpy에서 사용되는 indexing은 python에서의 indexing과 기본적으로 동일하다.
* 0부터 시작한다.

In [ ]:
# 1. np.arange([star,]stop, [, step], dtype = None)함수
# ndarray 생성

from IPython.display import Image

display(Image('./images/22.데이터분석_numpy_03_arange.png', width=500, height=300))

In [ ]:
# 1) 1차원 indexing, slicing

arr = np.arange(10)
print(arr)
print(arr[:])
print(arr[0:])
print(arr[0:5])
print(arr[:5])
print(arr[:-1])

In [ ]:
# 2) 2차원 indexing, slicing
# 2차원 [,] or [:,:]

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[0,0], arr[0,1], arr[0,2])

In [ ]:
# slicing
# 다차원배열의 요소 중 복수개의 값에 접근
print(arr[0,])
print(arr[1,])
print()
print(arr[:,:])
print(arr[0:,0:])
print(arr[:2,:2])
# print(arr[,]) 에러
print(arr[:], '\n=\n', arr[:,:])

In [ ]:
print(arr[2:], arr[2:].shape)  # 2차원
print(arr[2, :], arr[2,:].shape)  # 1차원

In [ ]:
display(Image('./images/22.데이터분석_numpy_04_slicing.png', width=500, height=300))

In [ ]:
# 실습문제

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

# 1. arr2에서 9를 출력
print(arr2[2:,2], '=', arr2[-1:,-1])

# 2. arr2에서 모든열의 세번째 요소 [3,6,9] 출력
print(arr2[:,2], '=', arr2[:, -1])

# 3. arr2에서 [[1,2],[4,5]] 출력
print(arr2[:2,:2])

# 4. arr2에서 [[5,6], [8,9]] 출력
print(arr2[1:, 1:])

In [ ]:
m = np.array([[ 0, 1, 2, 3, 4],
              [ 5, 6, 7, 8, 9],
              [10,11,12,13,14]])

m = np.arange(15).reshape(3,5)

# 5. m행렬에서 값 7을 인덱싱하세요.
print(m[1,2])

# 6. m 행렬에서 배열 [6,7]을 슬라이싱하세요.
print(m[1, 1:3])

# 7. m 행렬에서 배열 [7,12]을 슬라이싱 하세요.
print(m[1:, 2])

# 8. m 행렬에서 배열 [[3,4],[8,9]]을 슬라이싱 하세요
print(m[0:2,3:5], '=\n', m[0:2, 3:])


# 9. 6,7,11,12를 2x2 ndarray로 슬라이싱 하시오.
print(m[1:, 1:3])


#### 4. 배열의 인덱싱

* numpy배열 객체의 강력한 기능은 `팬시 인덱싱 Fancy Indexing`이라고 부르는 배열 인덱싱이다.
* 인덱싱이란 이름을 붙었지만 `데이터베이스 질의(query)기능을 수행`한다.
* 배열의 인덱싱은 2가지가 있다.
    - 정수배열인덱싱
    - 블리언배열인덱싱
    
* 블리언배열 인덱싱은 `배열의 원소가 True or False 두가지 값으로만 구성`되며 인덱스 배열의 크기가 원래 ndarray객체의 크기와 동일해야 한다.

In [ ]:
# 1. 1차원 배열 불리언인덱싱

a = np.array([1,2,3,4,5,6,7,8,9,10])
idx = np.array([True, False, True, False, True, False, True, False,True, False])

print(a)
print(idx)

print(a[idx])
print(a[a%2==1])
print(a[a%2==0])

In [ ]:
a = np.arange(1,10).reshape(3,3)
idx = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])

print(a[idx])
print(a[a%2==0])
print(a[a%2==1])
print(a[a%3==0])

# 홀수이면 3의 배수 출력(& , | 이용)

print(a[(a%2==1) & (a%3==0)])

#### 5. Numpy 관련 함수

##### 1. 한개의 array에 적용되는 함수

In [ ]:
# 1. zeros() : array가 생성될 때 모든 요소의 값을 0으로 초기화

z1 = np.zeros(10)
print(z1)

z2 = np.zeros((3,5))
print(z2)

z3 = np.zeros((3,5), dtype = int)
print(z3)

z4 = np.zeros((3,5), dtype = 'float64')
print(z4)

z5 = np.zeros((3,5), dtype = np.float64)
print(z5)

In [ ]:
# 2. ones() : array가 생성될 때 모든 요소의 값을 1로 초기화

o = np.ones(10)
print(o)

o = np.ones((3,5), dtype = np.int32)
print(o)

In [ ]:
# 3. arange()
print(np.arange(10, 20, 2, dtype = int))

In [ ]:
# 4. random()
# 1) seed() : seed설정

np.random.seed(42)
print(np.random.rand(10))
print()

# 2) 난수를 발생 3가지 방법
# a. rand() : 0<=x<1사이의 난수 발생
print(np.random.rand(3,5))
print()

# b. randn() : 표준정규분포(가우시안)
print(np.random.randn(3,5))
print()

# c. randint() : 균인분포 정수
# np.random.randint(low, high, size, dtype), low ~ high-1 난수 중 정수
print(np.random.randint(10))
print(np.random.randint(10, size=5))
print(np.random.randint(10, 20, size=5))

In [ ]:
# 5. square() : 제곱근

arr1 = np.random.randn(5,3)
print(np.abs(arr1))
print()
print(np.square(arr1))

In [ ]:
# 6. exp() : 각 요소의 무리수 e지수로 연산
print(np.exp(arr1))

In [ ]:
# 7. log(), log10(), log2()
# 자연로그, 상용로그, 밑2인 로그

print(np.log(arr1))
print()
print(np.log10(arr1))
print()
print(np.log2(arr1))

In [ ]:
# 8. floor() : 바닥, ceil() : 천장 : 소수점 무시하고 아래정수, 위 정수

print(np.ceil(1.15156516))
print(np.floor(1.15156516))


print(np.floor(arr1))
print(np.ceil(arr1))
arr1

In [ ]:
# 9. isnan() : 요소의 값이 nan일 경우 True, 아닐 경우 False 리턴

print(np.log(arr1))
print(np.isnan(np.log(arr1)))
print('결측치 개수 = ', np.isnan(np.log(arr1)).sum())

#### 2. 2개의 array에 적용되는 함수

In [ ]:
np.random.seed(42)

arr1 = np.random.randn(5,3)
arr2 = np.random.randn(5,3)
print(arr1)
print(arr2)

In [ ]:
# 1. 사칙연산 : add, subtract, multiply, divide
print('더하기', np.add(arr1, arr2))
print('빼기', np.subtract(arr1, arr2))
print('곱하기', np.multiply(arr1, arr2))
print('나누기', np.divide(arr1, arr2))

In [ ]:
# 2. minumun() / maximum()

print('최댓값 = \n', np.maximum(arr1, arr2))
print('최솟값 = \n', np.minimum(arr1, arr2))

#### 3. 통계함수

* 통계함수를 통해서 numpy배열의 총합 or 평균 등을 구할 때 유용한 함수들이다.
* 열의 합 or 행의 합 등을 쉽게 구할 수 있다.

In [ ]:
# 1. sum() : 합계
# np.sum? axis = None(전체), 0 = 열의 합계, 1 = 행의 합계
print(arr1)
print()
print('전체 합 = ', np.sum(arr1))
print()
print('열의 합 = ', np.sum(arr1, axis = 0))
print()
print('행의 합 = ', np.sum(arr1, axis = 1))

In [ ]:
# 2. mean() : 평균

print(arr1)
print()
print('전체 평균 = ', np.mean(arr1))
print()
print('열의 평균 = ', np.mean(arr1, axis = 0))
print()
print('행의 평균 = ', np.mean(arr1, axis = 1))

In [ ]:
# 3. std() : 표준편차, var() : 분산, min() : 최소값, max() : 최대값
# median() : 중간값, percetile() 사사분위수..

from IPython.display import Image

display(Image('./images/22.데이터분석_numpy_05_statistic.png'))
display(Image('./images/22.데이터분석_numpy_06_statistic.png'))

In [ ]:
# 1) std() : 표준편차
a = [175, 177, 179, 181, 183]
print(np.std(a))

b = [[1,2,3],[4,5,6]]
print(np.std(b))
print(np.std(b, axis = 0))
print(np.std(b, axis = 1))

In [ ]:
# 2) var() : 분산
a = [175, 177, 179, 181, 183]
print(np.var(a))

b = [[1,2,3],[4,5,6]]
print(np.var(b))
print(np.var(b, axis = 0))
print(np.var(b, axis = 1))

In [ ]:
# 3) max() / min()
print(np.min(a))
print(np.min(b))
print(np.min(b, axis = 0))
print(np.min(b, axis = 1))
print()
print(np.max(a))
print(np.max(b))
print(np.max(b, axis = 0))
print(np.max(b, axis = 1))

In [ ]:
# 4) median() : 중간값
print(np.median(a))
print(np.median(b))
print(np.median(b, axis=0))
print(np.median(b, axis=1))

In [ ]:
# 5) percetile() : 사분위 수
# np.percentile?

print(np.percentile(a, 25)) # 1/4지점
print(np.percentile(a, 50))
print(np.percentile(a, 75))


print(np.percentile(b, 75))
print(np.percentile(b, 75, axis = 0))
print(np.percentile(b, 75, axis = 1))

In [ ]:
# 이상치 : IRQ(Q3-Q1)*1.5

In [ ]:
# 4. 위치 함수 : argmin(), argmax()
# 배열의 최소값/최대값의 위치를 리턴

print(a)
print(np.argmin(a))
print(b)
print(np.argmin(b))
print(np.argmin(b, axis = 0))
print(np.argmin(b, axis = 1))
print()
print(np.argmax(a))
print(np.argmax(b))
print(np.argmax(b, axis = 0))
print(np.argmax(b, axis = 1))

In [ ]:
# 5. cumsum() : 누적합 / cumprod() : 누적곱

print(a)
print(np.cumsum(a))
print(np.cumsum(b))
print(np.cumsum(b,axis=0))
print(np.cumsum(b,axis=1))

#### 4. 기타 함수

In [ ]:
# 1. sort() : 정렬
# np.sort?

arr = np.array([5,4,3,2,1])
print(arr, '->', np.sort(arr))

# 행별 정렬
arr = np.array([[5,4,6,3,2,1],['x', 'a', 'y', 'b', 'z', 'c']])
print(arr, '->\n', np.sort(arr))

In [ ]:
# 특정행만 정렬

print(np.sort(arr[1]))
print(np.sort(arr)[1])

print(np.sort(arr)[-2])
print(np.sort(arr)[:1])  # 2차원
print(np.sort(arr)[:-1]) # 2차원

In [ ]:
#  행 or 열별 정렬
print(arr)
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=1))

In [ ]:
# 2. unique() : 중복제거 함수

# 1) 1차원
names = np.array(['홍길동', '손흥민', '홍길순', '손흥민', '홍길동', '홍미녀'])
print(np.unique(names))

In [ ]:
# 2) 2차원
values = np.array([[1,2],[1,2], [2,3]])
print(np.unique(values))
print(np.unique(values, axis=0))
print(np.unique(values, axis=1))

In [ ]:
# 3) 주의할 점 : 요소의 개수가 다를 경우

values = np.array([[1,2], [1,2], [2,3,1]])

print(np.unique(values))

# print(np.unique(values, axis=0)) 오류
# print(np.unique(values, axis=1))

In [ ]:
# 1. data에 전체에 루트를 적용한 결과를 ndarray에 저장하세요
data = [1,2,3,4,5]

arr = np.sqrt(data)
print(arr, type(arr))

In [ ]:
# 2. 중간고사의 국어점수(10), 영어점수(20)
# 기말고사 국어점수(14), 영어점수(16)이 저장되어 있습니다.
# 과목별 평균점수 출력하세요

score = np.array([
    [10, 20],   # 중간고사
    [14, 16]   # 기말고사
])

print(score.mean(axis=0))
print(np.mean(score, axis=0))


In [ ]:
# 3. 2번에서 중간고사와 기말고사의 표준편차를 출력하세요
print(score.std(axis=1))
print(np.std(score, axis=1))

In [ ]:
# 4. 다음 배열에서 3보다 크고 7보다 작은 수만 추출하세요
arr = np.arange(10)

print(arr[(arr>3) & (arr<7)])

In [ ]:
# 5. 다음 ndarray 객체에서 음수를 출력하세요
arr = np.array([-1,2,-3,4])

print(arr[arr<0])

In [ ]:
# 6. 5번 arr에서 음수를 0으로 치환하세요
arr = np.array([-1,2,-3,4])

arr[arr<0] = 0
print(arr)

In [ ]:
# 7. 5번 arr에서 음수를 양수로 변환하세요
arr = np.array([-1,2,-3,4])

arr[arr<0] = -arr[arr<0]
print(arr)

In [ ]:
# 8. 양수 혹은 0이면 10을 더하고, 음수이면 10을 빼시오
arr = np.array([-1,2,-3,4])

arr[arr>=0] = arr[arr>=0] + 10
arr[arr<0] = arr[arr<0] - 10
print(arr)

In [ ]:
# where함수

# np.where?
np.where(arr>=0, arr+10, arr-10)
print(arr)

#### 5. 파일 입출력

* savetxt() : 파일저장
* loadtxt() : 파일로딩

In [ ]:
# 1. savetxt(filename, data, fmt, delimiter(구분자))
# np.savetxt?

import random

numbers = np.zeros((10, 4))
numbers

for i in range(10):
    for j in range(4):
        numbers[i][j] = random.randint(1000, 40000)
#         numbers[i,j] = random.randint(1000, 40000)
        
print(numbers)

# 파일 저장
np.savetxt('./data/save.csv', numbers, fmt='%d', delimiter=',')

In [ ]:
# 2. loadtxt()

# np.loadtxt?

f = np.loadtxt('./data/save.csv', delimiter=',')

print(f, '\n', type(f))

#### 6. 데이터분석 실습 - 영화 평점 데이터

* http://grouplens.org/datasets/movielens

In [ ]:
# 1. 영화 평점 데이터 로드 : ratings.dat

data = np.loadtxt('./data/movie/ratings.dat', delimiter='::', dtype = np.int64)
print(data.shape)

In [ ]:
# 첫 5행만 출력
data[:5]

In [ ]:
# 백만 ~ 백만 10건 출력
data[1000000:1000010, :3]

In [ ]:
# 실습
# 1. 전체 평점의 평균?
mean_rating_total = data[:, 2].mean()
print('전체평점의평균 = ', mean_rating_total.round(2))

In [ ]:
# 2. 사용자 총인원수? 사용자 ID별
user_ids = np.unique(data[:,0]).shape[0]
print('사용자 총 인원수 = ', user_ids)

In [ ]:
# 3. 사용자 ID = 1000인 사용자만 추출
data_for_user = data[data[:,0]==1000]
print('1000 ID 사용자의 건수 = ',data_for_user.shape[0])

In [ ]:
# 4. 사용자 ID = 1000인 사용자의 평균 평점?
print('1000 ID 사용자의 평균 평점 = ', data_for_user[:, 2].mean().round(2) )

In [ ]:
###### 5. 사용자별로 평점의 평균을 구하기

mean_value = []

used_ids = np.unique(data[:, 0])

for used_id in used_ids:
    # 1. 사용자별 data
    data_for_user = data[data[:,0]==used_id]
#     print(data_for_user)
#     break
    # 2. 사용자별 평점 평균
    value = data_for_user[:,2].mean().round(2)
    
    # 3. id와 평균을 리스트에 추가 
    mean_value.append([used_id, value])
    
print(mean_value)


In [ ]:
# 6. list자료형을 ndarray로 변환 후 savetxt()로 결과저장

mean_arry = np.array(mean_value, dtype = np.float32)
print(mean_arry.shape)
print(mean_arry[:5])

# 7. 결과파일 저장
np.savetxt('./data/movie/user_rating_mean.csv', mean_arry, delimiter=',', fmt='%.2f')

#### 7. 연습문제

##### 1) 영화별 평점의 평균구하기 : 표시 예 - [1, 'Toy Story (1995), 4.12]

* data cleansing(데이터 정제 작업) : movies.dat 파일 -> 3845 삭제 -> movies_utf8.dat저장
* 영화 평점 : ratings.dat  `UserID::MovieID::Rating::Timestamp`
* 영화 제목 : movie_utf8.dat `MovieID::Title::Genres`

In [ ]:
# 데이터 가져오기

data_ratings = np.loadtxt('./data/movie/ratings.dat', delimiter='::', dtype=np.int64)
data_movies = np.loadtxt('./data/movie/movies_utf8.dat', delimiter='::', dtype=np.str_, encoding='utf-8')

In [ ]:
# 데이터 확인
print(data_ratings[:5])
print(data_movies[:5])
print(data_ratings.shape, data_movies.shape)

In [ ]:
# 1. 영화 평점

print(data_movies[data_movies[:, 0]=='1000'])

print(data_movies[:, 0])   # movie_id 중복이 없음
print(data_ratings[:, 1])  # movie_id 중복이 있음

In [ ]:
# 2. 영화ID가 1
data_movies[data_movies[:, 0]==str(1), 0:2]

In [ ]:
# 3. ratings.dat에서 영화ID가져오기 : 중복제거
# np.unique(data_ratings[:, 1]).shape

movie_ids = np.unique(data_ratings[:, 1]) # 영화 id 저장
# print(movie_ids)

mean_values = []

for movie_id in movie_ids:
    
    # 1. movie_id와 같은 자료만 추출
    data_for_movie = data_ratings[data_ratings[:,1]==movie_id, :3]
#     print(data_for_movie)
#     break
    
    # 2. 영화별 평점 평균
    value = data_for_movie[:, 2].mean().round(2)
#     print(value)
#     break
    
    # 3. 영화제목
    movie_name = data_movies[data_movies[:,0] == str(movie_id),1]
#     print(movie_name)
#     break

    # 4. 리스트 저장
    mean_values.append([movie_id, movie_name, value])
    

print(mean_values[:3])

In [ ]:
# 결과저장

mean_array = np.array(mean_values)
np.savetxt('./data/movie/movie_rating_mean.csv', mean_array, fmt='%s', delimiter=',')